#!/bin/bash

# Small helper to build all the things (release), that is, .deb and .rpm too,
# using the musl target

set -e
set -u
set -E
set -o pipefail

cargo build --release --target x86_64-unknown-linux-musl
cargo deb --target x86_64-unknown-linux-musl
cargo generate-rpm --target x86_64-unknown-linux-musl
